#|
 This file is a part of cl-mpg123
 (c) 2016 Shirakumo http://tymoon.eu (shinmera@tymoon.eu)
 Author: Nicolas Hafner <shinmera@tymoon.eu>
|#

(in-package #:org.shirakumo.fraf.mpg123)

(defvar *id3v1-genre-list*
  (list ;; ID3V1 Spec
        "Blues"
        "Classic Rock"
        "Country"
        "dance"
        "Disco"
        "Funk"
        "Grunge"
        "Hip-Hop"
        "Jazz"
        "Metal"
        "New Age"
        "Oldies"
        "Other"
        "Pop"
        "Rhythm and Blues"
        "Rap"
        "Reggae"
        "Rock"
        "Techno"
        "Industrial"
        "Alternative"
        "Ska"
        "Death Metal"
        "Pranks"
        "Soundtrack"
        "Euro-Techno"
        "Ambient"
        "Trip-Hop"
        "Vocal"
        "Jazz & Funk"
        "Fusion"
        "Trance"
        "Classical"
        "Instrumental"
        "Acid"
        "House"
        "Game"
        "Sound Clip"
        "Gospel"
        "Noise"
        "Alternative Rock"
        "Bass"
        "Soul"
        "Punk"
        "Space"
        "Meditative"
        "Instrumental Pop"
        "Instrumental Rock"
        "Ethnic"
        "Gothic"
        "Darkwave"
        "Techno-Industrial"
        "Electronic"
        "Pop-Folk"
        "Eurodance"
        "Dream"
        "Southern Rock"
        "Comedy"
        "Cult"
        "Gangsta"
        "Top 40"
        "Christian Rap"
        "Pop / Funk"
        "Jungle"
        "Native US"
        "Cabaret"
        "New Wave"
        "Psychedelic"
        "Rave"
        "Showtunes"
        "Trailer"
        "Lo-Fi"
        "Trival"
        "Acid Punk"
        "Acid Jazz"
        "Polka"
        "Retro"
        "Musical"
        "Rock 'n' Roll"
        "Hard Rock"
        ;; Winamp Extensions
        "Folk"
        "Folk-Rock"
        "National Folk"
        "Swing"
        "Fast Fusion"
        "Bebop"
        "Latin"
        "Revival"
        "Celtic"
        "Bluegrass"
        "Avantgarde"
        "Gothic Rock"
        "Progressive Rock"
        "Psychedelic Rock"
        "Symphonic Rock"
        "Slow Rock"
        "Big Band"
        "Chorus"
        "Easy Listening"
        "Acoustic"
        "Humour"
        "Speech"
        "Chanson"
        "Opera"
        "Chamber Music"
        "Sonata"
        "Symphony"
        "Booty Bass"
        "Primus"
        "Porn Groove"
        "Satire"
        "Slow Jam"
        "Club"
        "Tango"
        "Samba"
        "Folklore"
        "Ballad"
        "Power Ballad"
        "Rhythmic Soul"
        "Freestyle"
        "Duet"
        "Punk Rock"
        "Drum Solo"
        "A capella"
        "Euro-House"
        "Dance Hall"
        "Goa"
        "Drum & Bass"
        "Club-House"
        "Hardcore Techno"
        "Terror"
        "Indie"
        "BritPop"
        "Negerpunk"
        "Polsk Punk"
        "Beat"
        "Christian Gangsta Rap"
        "Heavy Metal"
        "Black Metal"
        "Crossover"
        "Contemporary Christian"
        "Christian Rock"
        "Merengue"
        "Salsa"
        "Trash Metal"
        "Anime"
        "Jpop"
        "Synthpop"
        "Abstract"
        "Art Rock"
        "Baroque"
        "Bhangra"
        "Big Beat"
        "Breakbeat"
        "Chillout"
        "Downtempo"
        "Dub"
        "EBM"
        "Electric"
        "Electo"
        "Electroclash"
        "Emo"
        "Experimental"
        "Garage"
        "Global"
        "IDM"
        "Illbient"
        "Industro-Goth"
        "Jam Band"
        "Krautrock"
        "Leftfield"
        "Lounge"
        "Math Rock"
        "New Romantic"
        "Nu-Breakz"
        "Post-Punk"
        "Post-Rock"
        "Psytrance"
        "Shoegaze"
        "Space Rock"
        "Trop Rock"
        "World Music"
        "Neoclassical"
        "Audiobook"
        "Audio Theatre"
        "Neue Deutsche Welle"
        "Podcast"
        "Indie Rock"
        "G-Funk"
        "Dubstep"
        "Garage Rock"
        "Psybient"))

(defun id3v1-genre (num)
  (or (nth num *id3v1-genre-list*) "Unknown"))

(defun id3v2-genre (genre)
  (let ((pos 0)
        (genres ()))
    (tagbody
     dispatch
       (cond ((<= (length genre) pos)
              (go end))
             ((char= (char genre pos) #\()
              (go start-bracket))
             (T
              (go read-rest)))
     start-bracket
       (incf pos)
       (if (char= (char genre pos) #\()
           (go read-rest)
           (go read-num))
     read-num
       (let ((start pos))
         (loop until (char= (char genre pos) #\)) do (incf pos))
         (pushnew (id3v1-genre (parse-integer genre :start start :end pos)) genres :test #'string-equal)
         (incf pos)
         (go dispatch))
     read-rest
       (pushnew (subseq genre pos) genres :test #'string-equal)
       (setf pos (length genre))
       (go dispatch)
     end
       (return-from id3v2-genre genres))))
